version: "3.9"

services:
  postgres:
    container_name: arbitrage_system_postgres
    image: postgres:14.5
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: arbitrage_system
      PG_DATA: /var/lib/postgresql/data
      TZ: America/Sao_Paulo  # Set the container timezone
      PG_TZ: America/Sao_Paulo  # Set the PostgreSQL timezone
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
# volumes:
  # db: